CREATE TABLE TaiKhoan(
	MaTK INT PRIMARY KEY IDENTITY(1, 1),
	TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
	MatKhauMaHoa VARCHAR(255) NOT NULL,
    	VaiTro TINYINT NOT NULL CHECK (VaiTro IN (0,1)), 
    	-- 0 = Admin, 1 = NhanVien
    	TrangThai TINYINT NOT NULL DEFAULT 1 CHECK (TrangThai IN (0,1,2))
    	-- 0 = KhoaVinhVien, 1 = HoatDong, 2 = TamKhoa
);
CREATE TABLE [Admin](
	IdAD INT PRIMARY KEY IDENTITY(1, 1),
	MaTK INT NULL REFERENCES TaiKhoan(MaTK)
		ON DELETE SET NULL,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	Email VARCHAR(50) UNIQUE,
	SoDienThoai VARCHAR(20) UNIQUE NOT NULL,
);

CREATE TABLE NhanVien(
	IdNV INT PRIMARY KEY IDENTITY(1, 1),
	MaNV VARCHAR(50) NULL,
	MaTK INT NULL REFERENCES TaiKhoan(MaTK)
		ON DELETE SET NULL,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	Email VARCHAR(50) UNIQUE,
	SoDienThoai VARCHAR(20) UNIQUE NOT NULL,
	ChucVu NVARCHAR(50) NOT NULL CHECK (ChucVu IN ('ThuThu', 'NhanVienPartTime', 'NhanVienFullTime'))
);

CREATE TABLE TAC_GIA (
    IdTG INT PRIMARY KEY IDENTITY(1, 1),
    MaTacGia VARCHAR(50) NULL, 
    TenTacGia NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE THE_LOAI (
    IdTL INT PRIMARY KEY IDENTITY(1, 1),
    MaTheLoai VARCHAR(50) NULL,  
    TenTheLoai NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE NHA_XUAT_BAN (
    IdNXB INT PRIMARY KEY IDENTITY(1, 1),
    MaNXB VARCHAR(50) NULL,  
    TenNXB NVARCHAR(255) NOT NULL
);
GO
	
CREATE TABLE SACH (
    IdS INT PRIMARY KEY IDENTITY(1, 1),
    MaSach VARCHAR(50) NULL,  
    TenSach NVARCHAR(255) NOT NULL,
    NamXuatBan INT NOT NULL CHECK (NamXuatBan > 0),
    GiaSach DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    AnhBia VARBINARY(MAX),
    IdNXB INT NOT NULL REFERENCES NHA_XUAT_BAN(IdNXB) ON DELETE NO ACTION,  
    IdTacGia INT NOT NULL REFERENCES TAC_GIA(IdTG) ON DELETE NO ACTION,  
    IdTheLoai INT NOT NULL REFERENCES THE_LOAI(IdTL) ON DELETE NO ACTION  
);
GO

CREATE TABLE The_Nhap (
    IdTN INT PRIMARY KEY IDENTITY(1, 1),
    MaTheNhap VARCHAR(50) NULL,
	IdS INT NOT NULL REFERENCES SACH(IdS) ON DELETE NO ACTION,
    IdNV INT NOT NULL REFERENCES NhanVien(IdNV) ON DELETE NO ACTION,
    NgayNhap DATE NOT NULL,
    TrangThai VARCHAR(50) NOT NULL CHECK (TrangThai IN ('DaNhap', 'ChuaNhap')),
    GiaNhap DECIMAL(10, 2) NOT NULL DEFAULT 0.00 CHECK (GiaNhap >= 0),
	TongTienNhap DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
	TongSoLuongNhap INT NOT NULL CHECK (TongSoLuongNhap > 0)
);
GO
	
CREATE TABLE Kho_Sach (
    IdK INT PRIMARY KEY IDENTITY(1, 1),  
    MaSach INT NOT NULL REFERENCES SACH(IdS) ON DELETE CASCADE,  
    SoLuongHienTai INT NOT NULL DEFAULT 0 CHECK (SoLuongHienTai >= 0),
    TrangThaiSach VARCHAR(50) NOT NULL DEFAULT 'HetSach' CHECK (TrangThaiSach IN ('ConSach', 'HetSach'))
);
GO